create table if not exists public.students (
  id bigint generated by default as identity primary key,
  teacher_name text not null,
  name text not null,
  last_lesson_number integer not null default 0,
  created_at timestamptz not null default now(),
  unique (teacher_name, name)
);

create table if not exists public.lesson_records (
  id bigint generated by default as identity primary key,
  teacher_name text not null,
  student_name text not null,
  lesson_number integer not null check (lesson_number > 0),
  class_date date,
  class_time text not null default '',
  attendance text not null default '',
  homework_status text not null default '',
  seriousness integer not null default 0,
  interaction integer not null default 0,
  raw_text text not null default '',
  feedback jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (teacher_name, student_name, lesson_number)
);

create index if not exists lesson_records_student_date_idx
on public.lesson_records (teacher_name, student_name, class_date desc);

create table if not exists public.group_classes (
  id text primary key,
  teacher_name text not null,
  class_info text not null,
  default_time text not null default '13:10-15:10',
  last_lesson_number integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.group_class_students (
  class_id text not null references public.group_classes(id) on delete cascade,
  name text not null,
  display_order integer not null default 0,
  primary key (class_id, name)
);

create table if not exists public.group_lesson_records (
  id bigint generated by default as identity primary key,
  class_id text not null references public.group_classes(id) on delete cascade,
  teacher_name text not null,
  lesson_number integer not null check (lesson_number > 0),
  class_date date,
  class_time text not null default '',
  raw_text text not null default '',
  teaching_content text not null default '',
  difficult_points text not null default '',
  absorption text not null default '',
  homework text not null default '',
  students jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id, lesson_number)
);
